export type Plan = {
  category: 'pli' | 'rpli'; slug: string; name: string; shortName: string;
  description: string; term: string; entryAge: string; sumAssured: string;
  payout: string; premiumBasis: string; highlights: string[];
};

export const plans: Plan[] = [
  {category:'pli',slug:'endowment-assurance-santosh',name:'PLI Endowment Assurance (Santosh)',shortName:'Santosh',description:'A Postal Life Insurance endowment plan combining life cover with a lump-sum maturity benefit and accrued bonus.',term:'Until selected maturity age: 35, 40, 45, 50, 55, 58 or 60',entryAge:'19 years onward, subject to the selected maturity age',sumAssured:'Premium tables are quoted per ₹5,000 sum assured',payout:'Sum assured plus eligible accrued bonus at maturity',premiumBasis:'Age-at-entry and maturity-age premium tables',highlights:['Life insurance with a defined maturity age','Monthly, quarterly, half-yearly and yearly modes','Premium table values for supported age combinations']},
  {category:'pli',slug:'whole-life-assurance-suraksha',name:'PLI Whole Life Assurance (Suraksha)',shortName:'Suraksha',description:'Long-duration Postal Life Insurance cover with premiums ceasing at a selected age and whole-life protection.',term:'Premiums generally cease at age 55, 58 or 60',entryAge:'19 to 55, depending on premium-ceasing age',sumAssured:'Premium tables are quoted per ₹5,000 sum assured',payout:'Whole-life assurance benefit with eligible bonus',premiumBasis:'Age-at-entry and premium-ceasing-age tables',highlights:['Long-term whole-life cover','Choice of premium-ceasing age','High declared bonus category compared with endowment plans']},
  {category:'pli',slug:'convertible-whole-life-assurance-suvidha',name:'PLI Convertible Whole Life Assurance (Suvidha)',shortName:'Suvidha',description:'Whole-life cover with an option after five years to convert to an endowment policy maturing at a selected age.',term:'First five years as whole life; conversion option thereafter',entryAge:'19 to 50 in the supplied PLI premium table',sumAssured:'Premium tables are quoted per ₹5,000 sum assured',payout:'Depends on whether the conversion option is exercised',premiumBasis:'Initial premium and post-conversion premium tables',highlights:['Conversion option after five years','Maturity choices shown for ages 50, 55 and 58','Separate premium rates before and after conversion']},
  {category:'pli',slug:'anticipated-endowment-assurance-sumangal',name:'PLI Anticipated Endowment Assurance (Sumangal)',shortName:'Sumangal',description:'A periodic money-back PLI policy providing scheduled survival benefits during the term and a final payment with bonus.',term:'15-year or 20-year term',entryAge:'19 to 45 for 15 years; up to 40 for 20 years in the supplied table',sumAssured:'Monthly rates are quoted per ₹5,000 sum assured',payout:'20% survival payments at intervals and 40% plus accrued bonus at maturity',premiumBasis:'Age band and selected 15- or 20-year term',highlights:['Periodic money-back benefits','Choice of 15-year or 20-year term','Final 40% benefit with accrued bonus']},
  {category:'pli',slug:'joint-life-assurance-yugal-suraksha',name:'PLI Joint Life Assurance (Yugal Suraksha)',shortName:'Yugal Suraksha',description:'Joint-life endowment assurance for spouses, priced using an equivalent age calculated from both lives.',term:'5 to 20 years, subject to equivalent age',entryAge:'Equivalent-age premium table starts at age 21',sumAssured:'Minimum ₹20,000; multiples of ₹10,000 in the supplied table',payout:'Joint-life endowment benefit under policy conditions',premiumBasis:'Equivalent age and policy term, quoted per ₹10,000',highlights:['One policy covering two spouses','Equivalent age derived from both ages','Special sum-assured rebate rules']},
  {category:'rpli',slug:'endowment-assurance-gram-santosh',name:'RPLI Endowment Assurance (Gram Santosh)',shortName:'Gram Santosh',description:'Rural Postal Life Insurance endowment cover with a selected maturity age, guaranteed sum assured and eligible bonus.',term:'Until selected maturity age: 35, 40, 45, 50, 55, 58 or 60',entryAge:'19 years onward, subject to maturity-age limits',sumAssured:'Premium tables are quoted per ₹1,000 sum assured',payout:'Sum assured plus eligible accrued bonus at maturity',premiumBasis:'Age-at-entry and maturity-age tables',highlights:['Designed under Rural Postal Life Insurance','Four premium payment frequencies','Official table rows used for supported combinations']},
  {category:'rpli',slug:'convertible-whole-life-gram-suvidha',name:'RPLI Convertible Whole Life Assurance (Gram Suvidha)',shortName:'Gram Suvidha',description:'Rural whole-life assurance that may be converted after five years into an endowment policy maturing at a chosen age.',term:'Conversion option after the first five years',entryAge:'19 to 45 in the supplied RPLI table',sumAssured:'Premium tables are quoted per ₹1,000 sum assured',payout:'Benefit depends on conversion choice and selected maturity age',premiumBasis:'Initial and converted monthly, quarterly, half-yearly and annual tables',highlights:['Whole-life protection with flexibility','Conversion to endowment after five years','Maturity options at 50, 55, 58 or 60']},
  {category:'rpli',slug:'anticipated-endowment-gram-sumangal',name:'RPLI Anticipated Endowment (Gram Sumangal)',shortName:'Gram Sumangal',description:'A rural periodic money-back assurance plan with scheduled survival payouts and a final benefit including eligible bonus.',term:'15-year or 20-year term',entryAge:'19 to 40 in the supplied premium tables',sumAssured:'Premium tables are quoted per ₹1,000 sum assured',payout:'Three 20% survival benefits, then 40% plus accrued bonus',premiumBasis:'Exact age and selected term across four frequencies',highlights:['Regular money-back milestones','15-year and 20-year options','Final payment includes eligible accrued bonus']},
  {category:'rpli',slug:'10-year-rural-pli-gram-priya',name:'10-Year RPLI (Gram Priya)',shortName:'Gram Priya',description:'A fixed 10-year Rural Postal Life Insurance money-back plan with survival benefits during the term.',term:'Fixed 10 years',entryAge:'20 to 45 in the supplied table',sumAssured:'Premium rates are quoted per ₹1,000 sum assured',payout:'20% after years 4 and 7; 60% plus accrued bonus after year 10',premiumBasis:'Age-at-entry table across four payment frequencies',highlights:['Simple fixed 10-year term','Money back at years 4 and 7','Final 60% benefit with accrued bonus']},
  {category:'rpli',slug:'children-policy-gram-bal-jeevan-bima',name:'RPLI Children Policy (Gram Bal Jeevan Bima)',shortName:'Gram Bal Jeevan Bima',description:'A Rural Postal Life Insurance children policy with premium rates based on age at conversion and maturity age.',term:'Maturity ages shown from 18 to 25 in the supplied annexure',entryAge:'Conversion ages shown from 14 to 24',sumAssured:'Extended premiums are quoted per ₹1,000 sum assured',payout:'Children policy benefit under applicable RPLI rules',premiumBasis:'Age on conversion and age at maturity',highlights:['Purpose-built children policy','Short remaining-term premium rows','Age-specific extended premium annexure']},
  {category:'pli',slug:'children-policy-bal-jeevan-bima',name:'PLI Children Policy (Bal Jeevan Bima)',shortName:'Bal Jeevan Bima',description:'Postal Life Insurance cover designed for children of eligible PLI policyholders, with maturity benefits subject to policy conditions.',term:'Child-specific term based on entry and maturity ages',entryAge:'Subject to the children-policy eligibility rules',sumAssured:'Selected within the limits applicable to the children policy',payout:'Sum assured and eligible bonus according to policy conditions',premiumBasis:'Child age, maturity age and selected sum assured',highlights:['Dedicated PLI children policy','Maturity-focused life cover','Bonus projection shown separately']},
  {category:'rpli',slug:'whole-life-assurance-gram-suraksha',name:'RPLI Whole Life Assurance (Gram Suraksha)',shortName:'Gram Suraksha',description:'Rural Postal Life Insurance whole-life protection with premiums payable up to a selected premium-ceasing age.',term:'Premiums generally cease at age 55, 58 or 60',entryAge:'Subject to the selected premium-ceasing age',sumAssured:'Rates scale with the selected sum assured',payout:'Whole-life assurance benefit with eligible accrued bonus',premiumBasis:'Entry age and premium-ceasing age',highlights:['Long-term rural life protection','Choice of premium-ceasing age','Premium and bonus shown separately']},
];

export const planPath=(plan:Plan)=>`/${plan.category}/${plan.slug}`;
export const findPlan=(category:string,slug:string)=>plans.find(p=>p.category===category&&p.slug===slug);
const calculatorIds:Record<string,string>={
 'endowment-assurance-santosh':'santosh','whole-life-assurance-suraksha':'suraksha','convertible-whole-life-assurance-suvidha':'suvidha','anticipated-endowment-assurance-sumangal':'sumangal','joint-life-assurance-yugal-suraksha':'yugal','children-policy-bal-jeevan-bima':'bal','endowment-assurance-gram-santosh':'gram-santosh','whole-life-assurance-gram-suraksha':'gram-suraksha','convertible-whole-life-gram-suvidha':'gram-suvidha','anticipated-endowment-gram-sumangal':'gram-sumangal','10-year-rural-pli-gram-priya':'gram-priya','children-policy-gram-bal-jeevan-bima':'gram-bal'
};
export const calculatorIdForPlan=(plan:Plan)=>calculatorIds[plan.slug];
export const planForCalculatorId=(id:string)=>plans.find(plan=>calculatorIdForPlan(plan)===id);
