import type { Metadata } from 'next';
import Link from 'next/link';
import { planPath, plans } from '@/lib/plans';
import { PolicyChecklist } from '@/components/policy-checklist';

export const metadata:Metadata={
 title:'PLI & RPLI Calculator User Guide and Policy Checklist',
 description:'Learn to estimate PLI and RPLI premiums, maturity value and net gain, then use the policyholder checklist to organise your bond, premiums, contact details and nomination.',
 alternates:{canonical:'/guides/postalplan-calculator-user-guide'},
};

const toc=[['what-is-postalplan','What is PostalPlan?'],['how-to-use','How to use the calculator'],['results','Understanding your results'],['policy-support','Supported PLI and RPLI plans'],['policy-checklist','PLI and RPLI checklist'],['what-changes','What changes an estimate?'],['tips','Planning tips'],['accuracy','Accuracy and limitations'],['faq','Frequently asked questions']];
const faqs=[
 ['Is PostalPlan an official India Post website?','No. PostalPlan is an independent planning tool. Confirm premiums, eligibility and benefits with India Post before purchasing or changing a policy.'],
 ['Does PostalPlan store my details?','No account is required, and the calculator does not store the values entered into the planning form.'],
 ['Why does a result say “official annexure rate found”?','It means the selected age and maturity combination matched a row transcribed from one of the supplied policy premium tables. Taxes, rebates, bonuses and underwriting can still affect an official quotation.'],
 ['What does “indicative estimate” mean?','The supplied documents did not contain a matching rate row for that exact selection, so PostalPlan uses a clearly labelled planning approximation.'],
 ['Can I compare payment frequencies?','Yes. Switch between monthly, quarterly, half-yearly and yearly to see how the instalment and total projected premium change.'],
 ['Is the maturity amount guaranteed?','The displayed maturity estimate combines the selected sum assured with a projected bonus. Bonus rates and policy benefits remain subject to applicable declarations and policy conditions.'],
];

export default function UserGuide(){
 const schema={'@context':'https://schema.org','@type':'FAQPage',mainEntity:faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))};
 return <main className="plan-page"><header className="topbar"><Link className="brand" href="/"><span className="brand-mark">प</span><span>PostalPlan</span></Link><Link className="back-link" href="/#calculator">Open calculator</Link></header>
  <article className="guide-article"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><span>User guide</span></nav><p className="eyebrow">POSTALPLAN HELP CENTRE</p><h1>How to use the PLI &amp; RPLI calculator</h1><p className="lead">A practical guide to estimating premiums, maturity value, bonus and net gain—and to knowing when a result is based on a supplied premium-table row.</p>
   <nav className="toc" aria-label="On this page"><strong>On this page</strong>{toc.map(([id,label],i)=><a key={id} href={`#${id}`}><span>{String(i+1).padStart(2,'0')}</span>{label}</a>)}</nav>
   <section id="what-is-postalplan"><p className="section-no">01</p><h2>What is PostalPlan?</h2><p>PostalPlan is a free planning calculator for Postal Life Insurance and Rural Postal Life Insurance. It helps you explore how policy choice, entry age, maturity age, sum assured and payment frequency can influence the estimated premium and maturity outcome.</p><p>The calculator brings the main figures into one view: first-year instalment, renewal instalment, projected total premium, accrued bonus, maturity amount and estimated gain over premiums. It is intended for comparison and preparation—not as a replacement for an official quotation.</p></section>
   <section id="how-to-use"><p className="section-no">02</p><h2>How to use the calculator</h2><div className="steps"><div><b>1</b><h3>Select a policy</h3><p>Choose the relevant PLI or RPLI plan. The plan determines the premium basis and bonus assumption.</p></div><div><b>2</b><h3>Enter policy details</h3><p>Add the current age, maturity or premium-ceasing age, and desired sum assured.</p></div><div><b>3</b><h3>Choose payment frequency</h3><p>Compare monthly, quarterly, half-yearly and yearly instalments.</p></div><div><b>4</b><h3>Review the result</h3><p>Check the rate-status message, premium breakdown, bonus, maturity and net gain.</p></div></div><div className="guide-callout"><strong>Start with the rate-status message</strong><p>“Official annexure rate found” confirms a matching table row. “Indicative estimate” means the result uses the fallback planning model.</p><Link href="/#calculator">Try the calculator →</Link></div></section>
   <section id="results"><p className="section-no">03</p><h2>Understanding your results</h2><dl className="glossary"><div><dt>Sum assured</dt><dd>The base insured amount selected for the policy, before adding bonus.</dd></div><div><dt>Year 1 premium</dt><dd>The estimated instalment after the rebate and first-year GST treatment used by the calculator.</dd></div><div><dt>Renewal premium</dt><dd>The estimated instalment from the second policy year onward.</dd></div><div><dt>Accrued bonus</dt><dd>A projection based on the plan’s bonus rate, sum assured and eligible term.</dd></div><div><dt>Maturity value</dt><dd>The projected sum assured plus accrued bonus shown by PostalPlan.</dd></div><div><dt>Net gain</dt><dd>Projected maturity value minus the estimated total premiums paid.</dd></div></dl></section>
   <section id="policy-support"><p className="section-no">04</p><h2>Supported PLI and RPLI plans</h2><p>PostalPlan includes the following policy choices. Each linked guide explains its term, premium-table basis and benefit pattern.</p><div className="policy-directory">{plans.map(p=><Link href={planPath(p)} key={p.slug}><small>{p.category.toUpperCase()}</small><strong>{p.shortName}</strong><span>{p.name}</span></Link>)}</div></section>
   <section id="policy-checklist"><p className="section-no">05</p><h2>PLI and RPLI policyholder checklist</h2><PolicyChecklist /></section>
   <section id="what-changes"><p className="section-no">05</p><h2>What changes an estimate?</h2><div className="factors"><div><h3>Entry age</h3><p>Premium rates commonly increase at later entry ages for an otherwise similar policy.</p></div><div><h3>Policy duration</h3><p>A longer payment or policy period changes both the instalment and the years over which bonus may accrue.</p></div><div><h3>Sum assured</h3><p>Premium and bonus scale with the insured amount. Eligible rebates can also depend on this value.</p></div><div><h3>Payment mode</h3><p>The amount per instalment and total number of instalments vary by payment frequency.</p></div><div><h3>GST and rebate</h3><p>PostalPlan includes these in the displayed premium estimate rather than showing only the base rate.</p></div><div><h3>Bonus assumptions</h3><p>The maturity projection changes when the applicable plan bonus rate or eligible term changes.</p></div></div></section>
   <section id="tips"><p className="section-no">06</p><h2>Tips for better scenario planning</h2><ul className="check-list"><li>Use the age on your next birthday when comparing against a table that defines entry age that way.</li><li>Test more than one maturity age or term instead of judging a policy from a single scenario.</li><li>Compare both the instalment affordability and total projected premium.</li><li>Look for the annexure-rate status before relying on a premium figure.</li><li>Keep survival benefits in mind for money-back plans; the final maturity payment may not represent every payment received.</li><li>Take your preferred scenario to India Post for an official quotation and eligibility check.</li></ul></section>
   <section id="accuracy"><p className="section-no">07</p><h2>Accuracy and limitations</h2><p>Where a matching row exists, PostalPlan uses the premium values transcribed from the policy tables supplied for this project and scales them to the selected sum assured. Some plans or combinations do not yet have a complete matching table in the app; these are visibly labelled as indicative.</p><div className="warning"><strong>Important</strong><p>Premium tables, bonus declarations, GST treatment, rebates, medical requirements and eligibility can change. PostalPlan is not India Post and does not issue policies. Always verify the final figures and terms with an authorised India Post representative.</p></div></section>
   <section id="faq"><p className="section-no">08</p><h2>Frequently asked questions</h2><div className="faq-list">{faqs.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section>
  </article><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/></main>;
}
